# Generated by Django 5.1.1 on 2024-09-27 15:21

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("about", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "eligibity_criteria",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "membership_benefits",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "certificate",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="memberships"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="memberships"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "qualification",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="members"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.membership",
                    ),
                ),
            ],
        ),
    ]
