# Generated by Django 4.2 on 2024-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_membership_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
