# Generated by Django 4.2 on 2024-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_membership_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="membershipId",
            field=models.CharField(
                default="IOASR/Fellow-536/2024", max_length=256, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="since",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
