# Generated by Django 4.2 on 2024-10-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_member_membershipid_member_since"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("qualification", models.CharField(max_length=255)),
                ("affiliation", models.CharField(max_length=255)),
                ("specialization", models.CharField(max_length=255)),
                ("institution", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="membership-application")),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="specialization",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
