# Generated by Django 5.0 on 2024-03-02 13:39

import django.db.models.deletion
from django_ckeditor_5 import fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_press', models.BooleanField(default=False)),
                ('url', models.TextField(blank=True, default=None, null=True)),
                ('article_type', models.CharField(choices=[('Research Article', 'Research Article'), ('Mini Review Article', 'Mini Review Article'), ('Commentary Article', 'Commentary Article'), ('Review Article', 'Review Article'), ('Short Communication', 'Short Communication'), ('Short Commentary Article', 'Short Commentary Article'), ('Case Report', 'Case Report'), ('Case Series', 'Case Series'), ('Clinical Images', 'Clinical Images'), ("Editor's pick", "Editor's pick"), ('Editorial', 'Editorial'), ('Elective Report', 'Elective Report'), ('Letter to the Editor', 'Letter to the Editor'), ('News Article', 'News Article'), ('News Section', 'News Section'), ('Original Article', 'Original Article'), ('Perspective Article', 'Perspective Article')], max_length=128, verbose_name='Article Type')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('doi', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='DOI')),
                ('doi_link', models.TextField(blank=True, default=None, null=True, verbose_name='DOI Link')),
                ('pmid', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='PMID')),
                ('pmid_link', models.TextField(blank=True, default=None, null=True, verbose_name='PMID Link')),
                ('abstract', fields.CKEditor5Field(blank=True, default=None, null=True)),
                ('page_from', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('page_to', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('keywords', models.TextField(blank=True, default=None, null=True)),
                ('how_to_cite', fields.CKEditor5Field(blank=True, default=None, null=True)),
                ('pdf', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('received', models.DateField(blank=True, default=None, null=True)),
                ('revised', models.DateField(blank=True, default=None, null=True)),
                ('accepted', models.DateField(blank=True, default=None, null=True)),
                ('published', models.DateField(blank=True, default=None, null=True)),
                ('available_on', models.DateField(blank=True, default=None, null=True)),
                ('is_open_access', models.BooleanField(default=True)),
                ('downloads', models.PositiveBigIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('apa', models.TextField(blank=True, default=None, null=True)),
                ('mla', models.TextField(blank=True, default=None, null=True)),
                ('chicago', models.TextField(blank=True, default=None, null=True)),
                ('vancouver', models.TextField(blank=True, default=None, null=True)),
                ('harvard', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_press', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32, verbose_name='Issue Name')),
                ('month', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Month')),
                ('is_special_issue', models.BooleanField(default=False, verbose_name='This is a Special Issue')),
                ('title', models.TextField(blank=True, default=None, null=True, verbose_name='Special Issue Title')),
                ('about', fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Special Issue About')),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Special Issue Cover')),
                ('submission_deadline', models.DateField(blank=True, default=None, null=True, verbose_name='Special Issue Submission Deadline')),
                ('is_published', models.BooleanField(default=False, verbose_name='This Speical Issue is published?')),
                ('published', models.DateField(blank=True, default=None, null=True, verbose_name='Special Issue Published Date')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Journal Name')),
                ('abbreviation', models.CharField(max_length=256, verbose_name='Abbreviation Name')),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
                ('issn_print', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='ISSN Print')),
                ('issn_online', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='ISSN Online')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('thumbnail', models.ImageField(upload_to='journal_thumbnails', verbose_name='Thumbnail')),
                ('about', fields.CKEditor5Field(blank=True, default=None, null=True)),
                ('aim_and_scope', fields.CKEditor5Field(blank=True, default=None, null=True)),
                ('apc', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Processing Charges')),
                ('cite_score', models.FloatField(default=0.0)),
                ('impact_factor', models.FloatField(default=0.0)),
                ('acceptance_rate', models.CharField(max_length=50, verbose_name='Acceptance Rate')),
                ('first_decision', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Time to First Decision (in days)')),
                ('acceptance_to_publication', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Acceptance to publication (in days)')),
                ('review_time', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Review Time')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('primary_color', models.CharField(default='#5C5470', max_length=20, verbose_name='Primary HEX Color code')),
                ('secondary_color', models.CharField(default='#352F44', max_length=20, verbose_name='Secondary HEX Color code')),
                ('light_color', models.CharField(default='#FAF0E6', max_length=20, verbose_name='Light HEX Color code')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Last Name')),
                ('email', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('orcid_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('affiliation', models.TextField(blank=True, default=None, null=True, verbose_name='Affilication')),
                ('qualification', models.TextField(blank=True, default=None, null=True, verbose_name='Qualification')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='journals.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('content', fields.CKEditor5Field(blank=True, default=None, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='journals.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journals.issue'),
        ),
        migrations.CreateModel(
            name='Indexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('link', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexings', to='journals.journal')),
            ],
        ),
        migrations.CreateModel(
            name='EditorialBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_type', models.CharField(choices=[('editor_in_chief', 'Editor-In-Chief'), ('managing_editor', 'Managing Editor'), ('associate_editor', 'Associate Editor'), ('editorial_board_member', 'Editorial Board Member'), ('advisory_board_member', 'Advisory Board Member')], default='editorial_board_member', max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('qualification', models.TextField(blank=True, default=None, null=True)),
                ('designation', models.TextField(blank=True, default=None, null=True)),
                ('institution', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='editors')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_board', to='journals.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='journals.journal')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='JournalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, default=None, null=True)),
                ('content', fields.CKEditor5Field(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='journals.journal')),
            ],
        ),
        migrations.CreateModel(
            name='JournalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, default=None, null=True)),
                ('content', fields.CKEditor5Field(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='journals.journal')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('content', fields.CKEditor5Field()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='journals.journal')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='SpecialIssueGuestEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Full Name')),
                ('email', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('orcid_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('affiliation', models.TextField(blank=True, default=None, null=True, verbose_name='Affilication')),
                ('qualification', models.TextField(blank=True, default=None, null=True, verbose_name='Qualification')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_editors', to='journals.issue')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journals.subject'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_press', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32, verbose_name='Volume Name')),
                ('year', models.CharField(max_length=32, verbose_name='Year')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='journals.journal')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journals.volume'),
        ),
    ]
