# Generated by Django 5.0 on 2024-03-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauthor',
            name='prefix',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Prefix'),
        ),
    ]
