# Generated by Django 5.0 on 2024-03-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_articleauthor_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_space_1', models.ImageField(upload_to='ads')),
                ('ad_space_2', models.ImageField(upload_to='ads')),
                ('responsive_ad_space_1', models.ImageField(upload_to='ads')),
                ('responsive_ad_space_2', models.ImageField(upload_to='ads')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_ads', to='journals.journal')),
            ],
            options={
                'verbose_name': 'Ad Config',
                'verbose_name_plural': 'Ad Config',
            },
        ),
    ]
