# Generated by Django 5.0 on 2024-03-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journaladconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaladconfig',
            name='ad_space_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ads'),
        ),
        migrations.AlterField(
            model_name='journaladconfig',
            name='ad_space_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ads'),
        ),
        migrations.AlterField(
            model_name='journaladconfig',
            name='responsive_ad_space_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ads'),
        ),
        migrations.AlterField(
            model_name='journaladconfig',
            name='responsive_ad_space_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ads'),
        ),
    ]
