# Generated by Django 5.0 on 2024-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_journaladconfig_ad_space_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaladconfig',
            name='ad_space_1_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journaladconfig',
            name='ad_space_2_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journaladconfig',
            name='responsive_ad_space_1_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journaladconfig',
            name='responsive_ad_space_2_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
