# Generated by Django 5.0 on 2024-03-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_journaladconfig_ad_space_1_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexing',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
