# Generated by Django 5.0 on 2024-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_indexing_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='xml',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
