# Generated by Django 5.0 on 2024-03-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_journal_submission_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='iarconsortium/articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='xml',
            field=models.FileField(blank=True, default=None, null=True, upload_to='iarconsortiumarticles'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/editors'),
        ),
        migrations.AlterField(
            model_name='indexing',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/indexings'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/issues', verbose_name='Special Issue Cover'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/journals'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='thumbnail',
            field=models.ImageField(upload_to='iarconsortium/journals', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='journaladconfig',
            name='ad_space_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/ads'),
        ),
        migrations.AlterField(
            model_name='journaladconfig',
            name='ad_space_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/ads'),
        ),
        migrations.AlterField(
            model_name='journaladconfig',
            name='responsive_ad_space_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/ads'),
        ),
        migrations.AlterField(
            model_name='journaladconfig',
            name='responsive_ad_space_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='iarconsortium/ads'),
        ),
    ]
