# Generated by Django 5.0 on 2024-07-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0009_alter_article_pdf_alter_article_xml_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="auto_generate_pdf",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="auto_generate_xml",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.TextField(default="title"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="editorialboard",
            name="editor_type",
            field=models.CharField(
                choices=[
                    ("editor_in_chief", "Editor-In-Chief"),
                    ("managing_editor", "Managing Editor"),
                    ("associate_editor", "Associate Editor"),
                    ("editorial_board_member", "Editorial Board Member"),
                    ("advisory_board_member", "Advisory Board Member"),
                    ("reviewer", "Reviewer"),
                ],
                default="editorial_board_member",
                max_length=32,
            ),
        ),
    ]
