# Generated by Django 5.1.1 on 2024-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "journals",
            "0010_article_auto_generate_pdf_article_auto_generate_xml_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="auto_generate_pdf",
        ),
        migrations.RemoveField(
            model_name="article",
            name="auto_generate_xml",
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="articles"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="xml",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="articles"
            ),
        ),
        migrations.AlterField(
            model_name="editorialboard",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="editors"
            ),
        ),
        migrations.AlterField(
            model_name="indexing",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="indexings"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="issues",
                verbose_name="Special Issue Cover",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="logo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="journals"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="thumbnail",
            field=models.ImageField(upload_to="journals", verbose_name="Thumbnail"),
        ),
        migrations.AlterField(
            model_name="journaladconfig",
            name="ad_space_1",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="ads"
            ),
        ),
        migrations.AlterField(
            model_name="journaladconfig",
            name="ad_space_2",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="ads"
            ),
        ),
        migrations.AlterField(
            model_name="journaladconfig",
            name="responsive_ad_space_1",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="ads"
            ),
        ),
        migrations.AlterField(
            model_name="journaladconfig",
            name="responsive_ad_space_2",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="ads"
            ),
        ),
    ]
